// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Zqk6sumodSCpA51RzObn-p758Fq-PQQ',
    appId: '1:728010821003:web:21c55ee8a6f0704dbcf38e',
    messagingSenderId: '728010821003',
    projectId: 'flutter-instagram-clone-e1c4b',
    authDomain: 'flutter-instagram-clone-e1c4b.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-e1c4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu8f-hKDuXxxR3HWX0IseHcMP15y2tQQE',
    appId: '1:728010821003:android:e51a27d80294f18bbcf38e',
    messagingSenderId: '728010821003',
    projectId: 'flutter-instagram-clone-e1c4b',
    storageBucket: 'flutter-instagram-clone-e1c4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeovin2WNY-UL1W-PLcKCujj8YYvsk9p8',
    appId: '1:728010821003:ios:e9697c72a72f31bfbcf38e',
    messagingSenderId: '728010821003',
    projectId: 'flutter-instagram-clone-e1c4b',
    storageBucket: 'flutter-instagram-clone-e1c4b.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeovin2WNY-UL1W-PLcKCujj8YYvsk9p8',
    appId: '1:728010821003:ios:f975a6121ee7e118bcf38e',
    messagingSenderId: '728010821003',
    projectId: 'flutter-instagram-clone-e1c4b',
    storageBucket: 'flutter-instagram-clone-e1c4b.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone.RunnerTests',
  );
}
